Feature/locations franchise
laytlat/team-project_best-team pull request #6
Opened 2022-12-24 21:22 UTC by Yurii-Haponiuk

2022-12-24 22:10 UTC, laytlat requested changes

2022-12-24 22:10 UTC, laytlat commented on src/sass/_locations-franchise.scss
> +  border-color: $button-hover-color;
При фокусі текст в середині кнопки має змінювати колір на білий

2022-12-24 22:10 UTC, laytlat commented on src/partials/locations-franchise.html
> +  <button type="button" class="button-location js-open-modal" data-modal="4">
Зміни тут `data-modal` на 6

2022-12-24 22:10 UTC, laytlat commented on src/partials/locations-franchise.html
> +  <button type="button" class="button-franchise js-open-modal" data-modal="5">
Зміни тут `data-modal` на 7

2022-12-24 22:10 UTC, laytlat commented on src/sass/_locations-franchise.scss
> +      width: 322px;
Цей `width` не потрібен

2022-12-24 22:10 UTC, laytlat commented on src/sass/_locations-franchise.scss
> +      margin-right: auto;
авто маржини також не потрібні

2022-12-24 22:10 UTC, laytlat commented on src/sass/_locations-franchise.scss
> +      justify-content: center;
`justify-content` не потрібен, текст і без нього відцентрований

2022-12-24 22:10 UTC, laytlat commented on src/sass/_locations-franchise.scss
> +.open-map__link {
Для цієї кнопки-посилання також потрібні стилі `hover` i `focus`

2022-12-24 22:10 UTC, laytlat commented on src/sass/_locations-franchise.scss
> +.button-submit {
На цій кнопці має бути  `cursor: pointer;` а також стилі `hover` i `focus`

2022-12-25 08:45 UTC, Yurii-Haponiuk commented on src/sass/_locations-franchise.scss
> +  border-color: $button-hover-color;
Привіт змінив і ще замітив що стрілочки не змінювали колір теж добавив)

2022-12-25 08:48 UTC, Yurii-Haponiuk commented on src/partials/locations-franchise.html
> +  <button type="button" class="button-location js-open-modal" data-modal="4">
ок

2022-12-25 08:48 UTC, Yurii-Haponiuk commented on src/partials/locations-franchise.html
> +  <button type="button" class="button-franchise js-open-modal" data-modal="5">
ок

2022-12-25 09:01 UTC, Yurii-Haponiuk commented on src/sass/_locations-franchise.scss
> +      width: 322px;
переробив на max-width бо якщо я його заберу то текст розповзеця і не буде як на шаблоні а відступами пробував теж не виходе

2022-12-25 09:05 UTC, Yurii-Haponiuk commented on src/sass/_locations-franchise.scss
> +      justify-content: center;
ок

2022-12-25 09:05 UTC, Yurii-Haponiuk commented on src/sass/_locations-franchise.scss
> +      margin-right: auto;
якщо я їх прибиру заголовоу вліво тікає

2022-12-25 10:16 UTC, Yurii-Haponiuk commented on src/sass/_locations-franchise.scss
> +.open-map__link {
ок

2022-12-25 10:16 UTC, Yurii-Haponiuk commented on src/sass/_locations-franchise.scss
> +.button-submit {
ок

2022-12-26 13:12 UTC, closed without merging